#!/usr/bin/env python3
"""Send one command to the running server, e.g.  sudo mc whitelist add Steve"""
import importlib.util
import sys

spec = importlib.util.spec_from_file_location("watch", "/usr/local/bin/mc-watch.py")
watch = importlib.util.module_from_spec(spec)
spec.loader.exec_module(watch)
print(watch.rcon(" ".join(sys.argv[1:]) or "list"))
